name: Ingest

on:
  workflow_dispatch:
  schedule:
    - cron: "45 1 * * 2-6"   # example: run after market close (adjust as you like)

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        shard: [0, 1, 2, 3]   # 4 shards -> set to [0..N-1] for N shards

    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests lxml databricks-sql-connector

      - name: Run ingest shard
        env:
          # --- Databricks (use your existing secrets) ---
          DATABRICKS_SERVER:    ${{ secrets.DATABRICKS_SERVER }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
          DATABRICKS_TOKEN:     ${{ secrets.DATABRICKS_TOKEN }}

          # --- Symbol loading / sharding ---
          SYMBOL_SOURCE: "sp500"
          # SP500_CSV: "data/sp500.csv"        # set if you commit a CSV fallback
          SHARDS: "4"
          SHARD_INDEX: "${{ matrix.shard }}"
          MIN_SYMBOLS_SHARD: "80"             # guard: ~500/4 = ~125; pick a safe floor

          # --- Backfill window (one-time big run) ---
          BACKFILL_YEARS: "10"                
          FORCE_RELOAD_DAYS: "3650"

          # --- Performance knobs ---
          WORKERS: "10"                       # per-runner threadpool for fetch()
          FETCH_TIMEOUT: "90"                 # seconds per ticker (skip if stuck)
          BATCH_ROWS: "5000"                  # rows per MERGE batch

          # --- Logging (optional) ---
          DEBUG: "0"
          VALIDATE_ONLY: "0"

        run: |
          python ingest.py
